language: rust

cache: cargo

rust:
  - beta
  - stable

matrix:
  include:
    - env: FEATURES=""
    - env: FEATURES="--features geo-types"

script:
  - cargo build --release $FEATURES && cargo test --release $FEATURES
