[package]

name = "geojson"
description = "Library for serializing the GeoJSON vector GIS file format"
version = "0.20.0"
authors = ["The GeoRust Developers <mods@georust.org>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/georust/geojson"
readme = "README.md"
documentation = "https://docs.rs/geojson/"
keywords = ["geojson", "gis", "json", "geo"]
edition = "2018"

[dependencies]
serde = "~1.0"
serde_json = "~1.0"
geo-types = { version = "0.6", optional = true }
num-traits = "0.2"
thiserror = "1.0.20"
derive_more = "0.99.9"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "parse"
harness = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
