on: [push, pull_request]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install cargo-all-features
        run: cargo install cargo-all-features
      - name: Build
        run: cargo build-all-features --verbose
      - name: Run tests
        run: cargo test-all-features --verbose
